
gameplay:
  meeting-cooldown: 120
  discussion-time: 60
  voting-time: 90
  entity-damage-factor: 0.5
  one-player-ends-game: true

detective:
  notebook-cooldown: 3

chat:
  range: 15
  falloff: 15
  block-dampening: 1